version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "nix-actions"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    target-branch: "rust-actions"
    schedule:
      interval: weekly
